let Dwarf =
    {
        strength: 0,
        dexterity: 0,
        constitution: 2,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        survival: 0,
        speed: 25,
        features: [darkvision, dwarven_resilience, dwarven_combat_training, tool_proficiency, stonecunning],
        proficiencies: [dwarven_combat_training, tool_proficiency, stonecunning],
        languages: ["Common", "Dwarvish"],
        sub_races: ["Hill Dwarf", "Mountain Dwarf"],
        hit_points: 0,
    };

let Hill_Dwarf =
    {
        strength: 0,
        dexterity: 0,
        constitution: 0,
        intelligence: 0,
        wisdom: 1,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 0,
        features: [dwarven_toughness],
        proficiencies: [],
        languages: [],
        sub_races: [],
        hit_points: 1,
    };

let Mountain_Dwarf =
    {
        strength: 2,
        dexterity: 0,
        constitution: 0,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 0,
        features: [],
        proficiencies: [dwarven_armor_training],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };

let Elf =
    {
        strength: 0,
        dexterity: 2,
        constitution: 0,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 1,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 30,
        features: [darkvision, fey_ancestry, trance],
        proficiencies: [keen_senses],
        languages: ["Common", "Elvish"],
        sub_races: ["High ELf", "Wood Elf"],
        hit_points: 0,
    };

let High_Elf =
    {
        strength: 0,
        dexterity: 0,
        constitution: 0,
        intelligence: 1,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 0,
        features: [cantrip, extra_language],
        proficiencies: [elf_weapon_training],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };

let Wood_Elf =
    {
        strength: 0,
        dexterity: 0,
        constitution: 0,
        intelligence: 0,
        wisdom: 1,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 5,
        features: [fleet_of_foot, mask_of_the_wild],
        proficiencies: [elf_weapon_training],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };


let Halfling =
    {
        strength: 0,
        dexterity: 2,
        constitution: 0,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 25,
        features: [lucky, brave, halfling_nimbleness],
        proficiencies: [],
        languages: ["Common", "Halfling"],
        sub_races: ["Lightfoot", "Stout"],
        hit_points: 0,
    };

let Lightfoot_Halfling =
    {
        strength: 0,
        dexterity: 0,
        constitution: 0,
        intelligence: 0,
        wisdom: 0,
        charisma: 1,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 0,
        features: [naturally_stealthy],
        proficiencies: [],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };

let Stout_Halfling =
    {
        strength: 0,
        dexterity: 0,
        constitution: 1,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 0,
        features: [stout_resilience],
        proficiencies: [],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };

let Human =
    {
        strength: 1,
        dexterity: 1,
        constitution: 1,
        intelligence: 1,
        wisdom: 1,
        charisma: 1,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 30,
        features: ["Common"],
        proficiencies: [extra_language],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };

let Dragonborn =
    {
        strength: 2,
        dexterity: 0,
        constitution: 0,
        intelligence: 0,
        wisdom: 0,
        charisma: 1,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 30,
        features: [],
        proficiencies: [],
        languages: ["Common", "Draconic"],
        sub_races: ["Black", "Blue", "Brass", "Bronze", "Copper", "Gold", "Green", "Red", "Silver", "Gold"],
        hit_points: 0,
    };

let dragon_black =
    {
            color: "Black",
            damage_type: "Acid",
            features: [damage_resistance_acid, breath_weapon_black],
    };

let dragon_blue =
    {
            color: "Blue",
            damage_type: "Lightning",
            features: [damage_resistance_lightning, breath_weapon_blue],
    };
let dragon_brass =
    {
            color: "Brass",
            damage_type: "Fire",
            features: [damage_resistance_fire, breath_weapon_brass],
    };

let dragon_bronze =
    {
            color: "Bronze",
            damage_type: "Lightning",
            features: [damage_resistance_lightning, breath_weapon_bronze],
    };

let dragon_copper =
    {
            color: "Copper",
            damage_type: "Acid",
            features: [damage_resistance_acid, breath_weapon_copper],
    };
let dragon_gold =
    {
            color: "Gold",
            damage_type: "Fire",
            features: [damage_resistance_fire, breath_weapon_gold],
    };
let dragon_green =
    {
            color: "Green",
            damage_type: "Poison",
            features: [damage_resistance_poison, breath_weapon_green],
    };
let dragon_red =
    {
            color: "Red",
            damage_type: "Fire",
            features: [damage_resistance_fire, breath_weapon_red],
    };
let dragon_silver =
    {
            color: "Silver",
            damage_type: "Cold",
            features: [damage_resistance_cold, breath_weapon_silver],
    };
let dragon_white =
    {
            color: "White",
            damage_type: "Cold",
            features: [damage_resistance_cold, breath_weapon_white],
    };

let Gnome =
    {
        strength: 0,
        dexterity: 0,
        constitution: 0,
        intelligence: 2,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 25,
        features: [darkvision, gnome_cunning],
        proficiencies: [],
        languages: ["Common", "Gnome"],
        sub_races: ["Forest Gnome", "Rock Gnome"],
        hit_points: 0,
    };

let Forest_Gnome =
    {
        strength: 0,
        dexterity: 1,
        constitution: 0,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 0,
        features: [natural_illusionist, speak_with_small_beasts],
        proficiencies: [],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };

let Rock_Gnome =
    {
        strength: 0,
        dexterity: 0,
        constitution: 1,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 0,
        features: [artificers_lore, tinker],
        proficiencies: [],
        languages: [],
        sub_races: [],
        hit_points: 0,
    };

let Half_Elf =
    {
        strength: 0,
        dexterity: 0,
        constitution: 0,
        intelligence: 0,
        wisdom: 0,
        charisma: 2,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 30,
        features: [extra_language, ability_score_bonus_two, darkvision, fey_ancestry, skill_versatility_two],
        proficiencies: [],
        languages: ["Common", "Elvish"],
        sub_races: [],
        hit_points: 0,
    };

let Half_Orc =
    {
        strength: 2,
        dexterity: 0,
        constitution: 1,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 30,
        features: [darkvision, menacing, relentless_endurance, savage_attacks],
        proficiencies: [],
        languages: ["Common", "Orc"],
        sub_races: [],
        hit_points: 0,
    };

let Tiefling =
    {
        strength: 0,
        dexterity: 0,
        constitution: 0,
        intelligence: 1,
        wisdom: 0,
        charisma: 2,
        strength_save: 0,
        dexterity_save: 0,
        constitution_save: 0,
        intelligence_save: 0,
        wisdom_save: 0,
        charisma_save: 0,
        acrobatics: 0,
        animal_handling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        slight_of_hand: 0,
        stealth: 0,
        speed: 30,
        features: [darkvision, hellish_resistance, infernal_legacy],
        proficiencies: [],
        languages: ["Common", "Infernal"],
        sub_races: [],
        hit_points: 0,
    };